before_script:
  - apt-get update -qq
  - apt-get install -y make
  - make install
  - pip3 install -U pip setuptools pipenv==9.0.3
  - pip3 --version
  - pipenv install
  - pipenv shell
  - python --version
  - pip3 show django | grep Version

django-tests:
  script:
    - cd src
    - python manage.py test



