#image: ubuntu:16.04

variables:
    POSTGRES_USER: "adega"
    POSTGRES_PASSWORD: "adega"
    POSTGRES_DB: "adega"
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: "5432"
    VERSION: "DEVELOPMENT"


services:
    - postgres:9.6
before_script:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
# apt-get --quiet=2 não é efetivo, com >> /dev/null só mostra erros da saída
# stderr
  - apt-get update --assume-yes >> /dev/null 
  - apt-get install --assume-yes  python3-pip libpq-dev postgresql-client >> /dev/null

  - pip3 install --quiet -r requirements.txt
  - pip3 show django | grep Version

django-tests:
      tags:
        - ubuntu
        - regular
      script:
        - cd src
        - python3 manage.py makemigrations degree
        - python3 manage.py makemigrations educator
        - python3 manage.py makemigrations submission
        - python3 manage.py makemigrations student 
        - python3 manage.py makemigrations admission 
        - python3 manage.py migrate
        - python3 manage.py test

