version: '3'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=adega
            - POSTGRES_PASSWORD=adega
            - POSTGRES_DB=adega
    web:
        build: .
        command: bash "./docker_scripts/on_docker_init.sh"
        volumes:
            - .:/adega
        ports:
            - "8000:8000"
        links:
            - db
        depends_on:
            - db
        environment:
            - POSTGRES_USER=adega
            - POSTGRES_PASSWORD=adega
            - POSTGRES_DB=adega
            - POSTGRES_HOST=adega_db_1
