version: '3'
services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=adega
            - POSTGRES_PASSWORD=adega
            - POSTGRES_DB=adega
    web:
        build: .
        command: python3 ./src/manage.py makemigrations degree
        command: python3 ./src/manage.py makemigrations uploads
        command: python3 ./src/manage.py makemigrations educator
        command: python3 ./src/manage.py migrate
        command: python3 ./src/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/adega
        ports:
            - "8000:8000"
        links:
            - db
        depends_on:
            - db
