version: '3'
services:
    db:
        restart: always
        image: postgres
        volumes:
            - ~/.docker-volumes/adega_db/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${pg_user}
            - POSTGRES_PASSWORD=${pg_password}
            - POSTGRES_DB=${pg_database}
    web:
        restart: always
        build:
            context: .
            dockerfile: ./docker_scripts/Dockerfile
        command: bash "./docker_scripts/on_docker_init_production.sh"
        volumes:
            - .:/adega
#        ports:
#            - "8000:8000"
        links:
            - db
        depends_on:
            - db
        environment:
            - POSTGRES_USER=${pg_user}
            - POSTGRES_PASSWORD=${pg_password}
            - POSTGRES_DB=${pg_database}
            - POSTGRES_HOST=adega_db_1
              #- SECRET_KEY=${token}
            - VERSION=PRODUCTION

    nginx:
        restart: always
        build: ./nginx/
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web
        links:
            - web:web
        volumes:
            - ./static:/adega/static
            - /etc/ssl:/ssl
