version: '3'
services:
    db:
        container_name: adega_db_1
        image: postgres
        environment:
            - POSTGRES_USER=adega
            - POSTGRES_PASSWORD=adega
            - POSTGRES_DB=adega
    web:
        container_name: adega_web_1
        build: 
            context: .
            dockerfile: ./docker_scripts/Dockerfile
        command: bash "./docker_scripts/on_docker_init.sh"
        volumes:
            - .:/adega
        ports:
            - "8000:8000"
        links:
            - db
        depends_on:
            - db
        environment:
            - POSTGRES_USER=adega
            - POSTGRES_PASSWORD=adega
            - POSTGRES_DB=adega
            - POSTGRES_HOST=adega_db_1
